const skills = [
  "cpp.png",
  "java.png",
  "flutterimg.png",
  "dart.png",
  "js1.png",
  "android.png",
  "mysql.png",
  "pgsql.png",
  "html.png",
  "css.png",
  "gcp.png",
  "andstudio.png",
  "nodejs.png",
  "express.png",
  "azure.png",
  "fbase.png",
  "git.png",
  "github.png",
];
export default skills;
